const fs = require('fs');

const template = `-- Generated by a65ToLua.js
local memoryOffset = 0x0
local programCounterStart = 0x0

local programData = {
    [DATA]
}

return {
    memoryOffset = memoryOffset,
    programCounterStart = programCounterStart,
    programData = programData
}`.trim();

const inputFile = process.argv[2];
const outputFile = process.argv[3];

const data = fs.readFileSync(inputFile);

// get bytes as hex numbers
const bytes = data.toString('hex').match(/.{1,2}/g);
const hex = bytes.map(b => `0x${b.toUpperCase()}`);

// chunk the array every 16 elements
const chunks = [];
let chunk = [];
for (let i = 0; i < hex.length; i++) {
    chunk.push(hex[i]);
    if (chunk.length === 16) {
        chunks.push(chunk);
        chunk = [];
    }
}

let output = template.replace('[DATA]', chunks.map(chunk => chunk.join(', ')).join(',\n    '));

// write output file
fs.writeFileSync(outputFile, output);